title: Two Guys Making Pizza
description: Authentic Neapolitan Pizza Catering - We bring the experience to you
url: "https://twoguysmakingpizza.com"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  pages:
    output: true

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation
navigation:
  - name: "Home"
    link: "/"
  - name: "Book Us"
    link: "/book/"
